services:
  backend:
    build: ./backend
    container_name: tumaqueta_backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: tumaqueta_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
